# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b13ca3ed0100d5d4ff423ed96ac64c454042ae80de8641bb71d43ca5ba31e69cb11ccb5547b87823db2e0ff4cc592fac08610a772c31fb40b58dc2ad7ad2f2e

test:
  secret_key_base: 102d4fafe3e03010a595b54d0599b8fafff9c8d2563b9ce2b188a3610adc9d8e2bd6a5a3055a1776c65d627269209986675fd96c4386da7e5b30b36123931b7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
